// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/kristensala/erply-test-v2/app/controllers"
	"github.com/kristensala/erply-test-v2/app/services"
)

// Injectors from wire.go:

func Init() *Initialization {
	client := ConnectToRedis()
	customerServiceImpl := services.CustomerServiceInit(client)
	customerControllerImpl := controllers.CustomerControllerInit(customerServiceImpl)
	initialization := NewInitialization(customerServiceImpl, customerControllerImpl)
	return initialization
}

// wire.go:

var cache = wire.NewSet(ConnectToRedis)

var customerServiceSet = wire.NewSet(services.CustomerServiceInit, wire.Bind(new(services.CustomerService), new(*services.CustomerServiceImpl)))

var customerControllerSet = wire.NewSet(controllers.CustomerControllerInit, wire.Bind(new(controllers.CustomerController), new(*controllers.CustomerControllerImpl)))
